name: Unfettered Treacle
favicon: null
layout_spectrum: 0.51011
typography_spectrum: 1
title: Unfettered Treacle - Novelist Todd R. Moody
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a5d70'
    - '#502313'
    - '#bebdce'
    - '#e5e8e8'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
