name: Unfettered Treacle
favicon: null
layout_spectrum: 0.51011
typography_spectrum: 1
title: Unfettered Treacle - Novelist Todd R. Moody
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75120643-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e5b2e'
    - '#69c26a'
    - '#8cfe8e'
    - '#22affe'
    - '#cf7f18'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
