name: Unfettered Treacle
favicon: null
layout_spectrum: 0.51011
typography_spectrum: 1
title: Unfettered Treacle - Novelist Todd R. Moody
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b131e'
    - '#ffffff'
    - '#18445f'
    - '#a5afae'
    - '#7c8b8e'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
