name: Unfettered Treacle
favicon: null
layout_spectrum: 0.49908
typography_spectrum: 1
title: Unfettered Treacle - Novelist Todd R. Moody
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#324a70'
    - '#dfe9ea'
    - '#8697a9'
    - '#141623'
    - '#94c180'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
